# Generated by Django 5.0.6 on 2024-05-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.IntegerField(db_column='codCargo', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'harrys_cargo',
            },
        ),
        migrations.CreateModel(
            name='CategoriaLibro',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'molina_categoria',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('papellido', models.CharField(blank=True, max_length=30, null=True)),
                ('sapellido', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField(auto_now_add=True, db_column='fecha_nacimiento', null=True)),
            ],
            options={
                'db_table': 'molina_persona',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'molina_comuna',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('idEditorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'molina_ditorial',
            },
        ),
        migrations.CreateModel(
            name='EstadoLibro',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Estado_libro_molina',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idFPago', models.IntegerField(db_column='codFormaPago', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(db_column='descripcion', max_length=200)),
            ],
            options={
                'db_table': 'molina_formapago',
            },
        ),
        migrations.CreateModel(
            name='GeneroLibro',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'molina_genero_libro',
            },
        ),
        migrations.CreateModel(
            name='GeneroPersona',
            fields=[
                ('idGenero', models.AutoField(db_column='id_genero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='genero', max_length=20)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'harrys_genero',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idIdioma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'molina_idioma',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('idNacionalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'molina_nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='OrigenLibro',
            fields=[
                ('idOrigen', models.IntegerField(primary_key=True, serialize=False)),
                ('origenLibro', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'molina_origen_libro',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'molina_pais',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'molina_provincia',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'molina_region',
            },
        ),
        migrations.CreateModel(
            name='TapaLibro',
            fields=[
                ('idTapaLibro', models.IntegerField(primary_key=True, serialize=False)),
                ('tapaLibro', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'molina_tapa_libro',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='venta.persona')),
                ('descuento', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'molina_cliente',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='comuna',
            field=models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.comuna'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.IntegerField()),
                ('codCargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venta.cargo')),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.persona')),
            ],
            options={
                'db_table': 'molina_empleado',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.formapago')),
            ],
            options={
                'db_table': 'molina_boleta',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.generopersona'),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='venta.categorialibro')),
                ('editorial', models.ForeignKey(db_column='id_editorial', on_delete=django.db.models.deletion.CASCADE, to='venta.editorial')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='venta.estadolibro')),
                ('genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, to='venta.generolibro')),
                ('idioma', models.ForeignKey(db_column='id_idioma', on_delete=django.db.models.deletion.CASCADE, to='venta.idioma')),
                ('origen', models.ForeignKey(db_column='id_origen', on_delete=django.db.models.deletion.CASCADE, to='venta.origenlibro')),
                ('tapa', models.ForeignKey(db_column='id_tapa', on_delete=django.db.models.deletion.CASCADE, to='venta.tapalibro')),
            ],
            options={
                'db_table': 'libro_molina',
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('idDetalleBoleta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleta', models.ForeignKey(db_column='id_boleta', on_delete=django.db.models.deletion.CASCADE, to='venta.boleta')),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, to='venta.libro')),
            ],
            options={
                'db_table': 'molina_detalle_boleta',
            },
        ),
        migrations.CreateModel(
            name='LibroEditorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.libro')),
            ],
            options={
                'db_table': 'molina_libro_editorial',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.persona')),
                ('Nacionalidad', models.ForeignKey(db_column='id_nacionalidad', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.nacionalidad')),
            ],
            options={
                'db_table': 'molina_autor',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.pais'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.CASCADE, to='venta.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='venta.region'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('idResena', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(max_length=1000)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, to='venta.libro')),
            ],
            options={
                'db_table': 'molina_resena',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(db_column='id_comuna', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.comuna')),
                ('direccion', models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.DO_NOTHING, to='venta.direccion')),
            ],
            options={
                'db_table': 'harrys_sucursal',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.sucursal'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.cliente'),
        ),
    ]
