# Generated by Django 5.0.6 on 2024-05-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='direccion',
            table='molina_direccion',
        ),
        migrations.AlterModelTable(
            name='estadolibro',
            table='molina_estado_libro',
        ),
    ]
